import { mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterAll, describe, expect, it } from '@jest/globals';
import { parseGenomeFile, parseGenomeLine, parseGenomeMetadata } from './genome-parser.js';

const TEST_DIR = join(tmpdir(), `asklepios-genome-parser-test-${Date.now()}`);

async function createTestFile(name: string, content: string): Promise<string> {
  await mkdir(TEST_DIR, { recursive: true });
  const filePath = join(TEST_DIR, name);
  await writeFile(filePath, content);
  return filePath;
}

afterAll(async () => {
  await rm(TEST_DIR, { recursive: true, force: true });
});

// ─── Sample 23andMe file content ────────────────────────────────────

const SAMPLE_HEADER = `# This data file generated by 23andMe at: Sun Mar 01 09:32:20 2020
#
# This file contains raw genotype data, including data that is not used in 23andMe reports.
# This data has undergone a general quality review however only a subset of markers have been
# individually validated for accuracy. As such, this data is suitable only for research,
# educational, and informational use and not for medical or other use.
#
# Below is a text version of your data.  Fields are TAB-separated
# Each line corresponds to a single SNP.  For each SNP, we provide its identifier
# (an rsid or an internal id), its location on the reference human genome, and the
# genotype call oriented with respect to the plus strand on the human reference sequence.
# We are using reference human assembly build 37 (also known as Annotation Release 104).
# Note that it is possible that data downloaded at different times may be different due to ongoing
# improvements in our ability to call genotypes. More information about these changes can be found at:
# https://you.23andme.com/p/some_user/tools/data/download/
#
# More information on reference human assembly builds:
# https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.13/
#
# rsid\tchromosome\tposition\tgenotype
`;

const SAMPLE_DATA_LINES = [
  'rs548049170\t1\t69869\tTT',
  'rs13328684\t1\t74792\t--',
  'rs9283150\t1\t565508\tAA',
  'i713426\t1\t567092\tCC',
  'rs116587930\tX\t2699555\tA',
  'rs2534636\tY\t2887478\tC',
  'rs199474761\tMT\t72\tT',
  'rs28358569\t2\t100341\tAG',
  'rs3094315\t3\t752566\tII',
  'rs12345678\t4\t123456\tDD',
  'rs99999999\t5\t654321\tDI',
];

function buildSampleFile(lines: string[], header: string = SAMPLE_HEADER): string {
  return `${header}${lines.join('\n')}\n`;
}

// ─── parseGenomeMetadata ────────────────────────────────────────────

describe('parseGenomeMetadata', () => {
  it('extracts generation date from header', async () => {
    const filePath = await createTestFile(
      'meta_v5_basic.txt',
      buildSampleFile(SAMPLE_DATA_LINES.slice(0, 1)),
    );
    const meta = await parseGenomeMetadata(filePath);

    expect(meta.generationDate).toBe('2020-03-01');
    expect(meta.source).toBe('23andMe');
  });

  it('extracts genome build from header', async () => {
    const filePath = await createTestFile(
      'meta_build_v5_.txt',
      buildSampleFile(SAMPLE_DATA_LINES.slice(0, 1)),
    );
    const meta = await parseGenomeMetadata(filePath);

    expect(meta.referenceGenome).toBe('GRCh37');
  });

  it('infers source version from filename', async () => {
    const filePath = await createTestFile(
      'genome_v5_test.txt',
      buildSampleFile(SAMPLE_DATA_LINES.slice(0, 1)),
    );
    const meta = await parseGenomeMetadata(filePath);

    expect(meta.sourceVersion).toBe('v5');
  });

  it('returns undefined sourceVersion when filename has no version', async () => {
    const filePath = await createTestFile(
      'genome_test.txt',
      buildSampleFile(SAMPLE_DATA_LINES.slice(0, 1)),
    );
    const meta = await parseGenomeMetadata(filePath);

    expect(meta.sourceVersion).toBeUndefined();
  });

  it('defaults to GRCh37 when no build info in header', async () => {
    const minimalHeader =
      '# Some header without build info\n# rsid\tchromosome\tposition\tgenotype\n';
    const filePath = await createTestFile(
      'meta_nobuild_v5_.txt',
      buildSampleFile(SAMPLE_DATA_LINES.slice(0, 1), minimalHeader),
    );
    const meta = await parseGenomeMetadata(filePath);

    expect(meta.referenceGenome).toBe('GRCh37');
  });

  it('parses GRCh38 build correctly', async () => {
    const header38 =
      '# Reference human assembly build 38\n# rsid\tchromosome\tposition\tgenotype\n';
    const filePath = await createTestFile(
      'meta_build38_v5_.txt',
      buildSampleFile(SAMPLE_DATA_LINES.slice(0, 1), header38),
    );
    const meta = await parseGenomeMetadata(filePath);

    expect(meta.referenceGenome).toBe('GRCh38');
  });
});

// ─── parseGenomeLine ────────────────────────────────────────────────

describe('parseGenomeLine', () => {
  const META = {
    generationDate: '2020-03-01',
    referenceGenome: 'GRCh37',
    source: '23andMe',
    sourceVersion: 'v5',
  };
  const PATIENT_ID = 'patient-test';
  const IMPORT_DATE = '2026-03-12T00:00:00.000Z';

  it('parses a standard homozygous SNP line', () => {
    const variant = parseGenomeLine('rs548049170\t1\t69869\tTT', PATIENT_ID, META, IMPORT_DATE);

    expect(variant).toBeDefined();
    expect(variant?.rsid).toBe('rs548049170');
    expect(variant?.chromosome).toBe('1');
    expect(variant?.position).toBe(69869);
    expect(variant?.genotype).toBe('TT');
    expect(variant?.patientId).toBe(PATIENT_ID);
    expect(variant?.source).toBe('23andMe');
    expect(variant?.referenceGenome).toBe('GRCh37');
    expect(variant?.sourceVersion).toBe('v5');
    expect(variant?.importDate).toBe(IMPORT_DATE);
  });

  it('parses a heterozygous SNP line', () => {
    const variant = parseGenomeLine('rs28358569\t2\t100341\tAG', PATIENT_ID, META, IMPORT_DATE);

    expect(variant).toBeDefined();
    expect(variant?.genotype).toBe('AG');
    expect(variant?.chromosome).toBe('2');
  });

  it('parses a no-call genotype (--)', () => {
    const variant = parseGenomeLine('rs13328684\t1\t74792\t--', PATIENT_ID, META, IMPORT_DATE);

    expect(variant).toBeDefined();
    expect(variant?.genotype).toBe('--');
  });

  it('parses internal 23andMe IDs (i-prefixed)', () => {
    const variant = parseGenomeLine('i713426\t1\t567092\tCC', PATIENT_ID, META, IMPORT_DATE);

    expect(variant).toBeDefined();
    expect(variant?.rsid).toBe('i713426');
    expect(variant?.genotype).toBe('CC');
  });

  it('parses haploid calls on X chromosome', () => {
    const variant = parseGenomeLine('rs116587930\tX\t2699555\tA', PATIENT_ID, META, IMPORT_DATE);

    expect(variant).toBeDefined();
    expect(variant?.chromosome).toBe('X');
    expect(variant?.genotype).toBe('A');
  });

  it('parses haploid calls on Y chromosome', () => {
    const variant = parseGenomeLine('rs2534636\tY\t2887478\tC', PATIENT_ID, META, IMPORT_DATE);

    expect(variant).toBeDefined();
    expect(variant?.chromosome).toBe('Y');
    expect(variant?.genotype).toBe('C');
  });

  it('parses mitochondrial variants', () => {
    const variant = parseGenomeLine('rs199474761\tMT\t72\tT', PATIENT_ID, META, IMPORT_DATE);

    expect(variant).toBeDefined();
    expect(variant?.chromosome).toBe('MT');
    expect(variant?.position).toBe(72);
    expect(variant?.genotype).toBe('T');
  });

  it('parses insertion genotype (II)', () => {
    const variant = parseGenomeLine('rs3094315\t3\t752566\tII', PATIENT_ID, META, IMPORT_DATE);

    expect(variant).toBeDefined();
    expect(variant?.genotype).toBe('II');
  });

  it('parses deletion genotype (DD)', () => {
    const variant = parseGenomeLine('rs12345678\t4\t123456\tDD', PATIENT_ID, META, IMPORT_DATE);

    expect(variant).toBeDefined();
    expect(variant?.genotype).toBe('DD');
  });

  it('parses insertion/deletion heterozygous genotype (DI)', () => {
    const variant = parseGenomeLine('rs99999999\t5\t654321\tDI', PATIENT_ID, META, IMPORT_DATE);

    expect(variant).toBeDefined();
    expect(variant?.genotype).toBe('DI');
  });

  it('skips comment lines', () => {
    const variant = parseGenomeLine('# This is a comment', PATIENT_ID, META, IMPORT_DATE);
    expect(variant).toBeUndefined();
  });

  it('skips empty lines', () => {
    expect(parseGenomeLine('', PATIENT_ID, META, IMPORT_DATE)).toBeUndefined();
    expect(parseGenomeLine('   ', PATIENT_ID, META, IMPORT_DATE)).toBeUndefined();
  });

  it('skips lines with fewer than 4 tab-separated fields', () => {
    const variant = parseGenomeLine('rs123\t1\t500', PATIENT_ID, META, IMPORT_DATE);
    expect(variant).toBeUndefined();
  });

  it('skips lines with invalid chromosome', () => {
    const variant = parseGenomeLine('rs123\t99\t500\tAA', PATIENT_ID, META, IMPORT_DATE);
    expect(variant).toBeUndefined();
  });

  it('skips lines with non-numeric position', () => {
    const variant = parseGenomeLine('rs123\t1\tABC\tAA', PATIENT_ID, META, IMPORT_DATE);
    expect(variant).toBeUndefined();
  });

  it('skips lines with negative position', () => {
    const variant = parseGenomeLine('rs123\t1\t-5\tAA', PATIENT_ID, META, IMPORT_DATE);
    expect(variant).toBeUndefined();
  });

  it('handles \\r\\r\\n line endings (Windows-style)', () => {
    const variant = parseGenomeLine('rs548049170\t1\t69869\tTT\r\r', PATIENT_ID, META, IMPORT_DATE);

    expect(variant).toBeDefined();
    expect(variant?.rsid).toBe('rs548049170');
    expect(variant?.genotype).toBe('TT');
  });

  it('generates unique IDs for each variant', () => {
    const v1 = parseGenomeLine('rs123\t1\t100\tAA', PATIENT_ID, META, IMPORT_DATE);
    const v2 = parseGenomeLine('rs456\t1\t200\tCC', PATIENT_ID, META, IMPORT_DATE);

    expect(v1).toBeDefined();
    expect(v2).toBeDefined();
    expect(v1?.id).not.toBe(v2?.id);
  });

  it('omits sourceVersion when metadata has none', () => {
    const metaNoVersion = { ...META, sourceVersion: undefined };
    const variant = parseGenomeLine('rs123\t1\t100\tAA', PATIENT_ID, metaNoVersion, IMPORT_DATE);

    expect(variant).toBeDefined();
    expect(variant?.sourceVersion).toBeUndefined();
  });
});

// ─── parseGenomeFile ────────────────────────────────────────────────

describe('parseGenomeFile', () => {
  it('parses all data lines from a sample file', async () => {
    const filePath = await createTestFile('full_v5_test.txt', buildSampleFile(SAMPLE_DATA_LINES));

    const variants: Awaited<ReturnType<typeof parseGenomeLine>>[] = [];
    for await (const variant of parseGenomeFile(filePath, 'patient-test')) {
      variants.push(variant);
    }

    expect(variants).toHaveLength(SAMPLE_DATA_LINES.length);
  });

  it('skips comment header lines', async () => {
    const filePath = await createTestFile(
      'header_v5_test.txt',
      buildSampleFile(['rs548049170\t1\t69869\tTT']),
    );

    const variants: Awaited<ReturnType<typeof parseGenomeLine>>[] = [];
    for await (const variant of parseGenomeFile(filePath, 'patient-test')) {
      variants.push(variant);
    }

    expect(variants).toHaveLength(1);
    expect(variants[0]?.rsid).toBe('rs548049170');
  });

  it('handles file with only comments (no data lines)', async () => {
    const filePath = await createTestFile('comments_only_v5_.txt', '# comment 1\n# comment 2\n');

    const variants: Awaited<ReturnType<typeof parseGenomeLine>>[] = [];
    for await (const variant of parseGenomeFile(filePath, 'patient-test')) {
      variants.push(variant);
    }

    expect(variants).toHaveLength(0);
  });

  it('propagates metadata to each variant', async () => {
    const filePath = await createTestFile(
      'meta_propagation_v5_test.txt',
      buildSampleFile(['rs548049170\t1\t69869\tTT']),
    );

    const variants: Awaited<ReturnType<typeof parseGenomeLine>>[] = [];
    for await (const variant of parseGenomeFile(filePath, 'patient-abc')) {
      variants.push(variant);
    }

    expect(variants).toHaveLength(1);
    const v = variants[0];
    expect(v).toBeDefined();
    expect(v?.patientId).toBe('patient-abc');
    expect(v?.source).toBe('23andMe');
    expect(v?.referenceGenome).toBe('GRCh37');
    expect(v?.sourceVersion).toBe('v5');
    expect(v?.importDate).toBeDefined();
  });

  it('handles mixed valid and invalid lines', async () => {
    const lines = [
      'rs123\t1\t100\tAA', // valid
      'rs456\t99\t200\tCC', // invalid chromosome
      'rs789\t2\t300\tTT', // valid
      'bad_line', // too few fields
      'rs012\t3\t400\tGG', // valid
    ];
    const filePath = await createTestFile('mixed_v5_test.txt', buildSampleFile(lines));

    const variants: Awaited<ReturnType<typeof parseGenomeLine>>[] = [];
    for await (const variant of parseGenomeFile(filePath, 'patient-test')) {
      variants.push(variant);
    }

    expect(variants).toHaveLength(3);
    expect(variants.map((v) => v?.rsid)).toEqual(['rs123', 'rs789', 'rs012']);
  });
});
