import { randomUUID } from 'node:crypto';
import { createReadStream } from 'node:fs';
import { createInterface } from 'node:readline';
import type { Chromosome, GeneticVariant } from '../schemas/genetic-variant.js';
import { chromosomeValues } from '../schemas/genetic-variant.js';

/**
 * 23andMe genome file metadata extracted from comment headers.
 */
export interface GenomeMetadata {
  generationDate: string | undefined;
  referenceGenome: string;
  source: string;
  sourceVersion: string | undefined;
}

const VALID_CHROMOSOMES = new Set<string>(chromosomeValues);

/**
 * Extract metadata from 23andMe genome file header comments.
 */
export async function parseGenomeMetadata(filePath: string): Promise<GenomeMetadata> {
  const stream = createReadStream(filePath, { encoding: 'utf-8' });
  const rl = createInterface({ input: stream, crlfDelay: Infinity });

  let generationDate: string | undefined;
  let referenceGenome = 'GRCh37';

  for await (const rawLine of rl) {
    const line = rawLine.replace(/\r/g, '');
    if (!line.startsWith('#')) break;

    // Extract generation date: "# This data file generated by 23andMe at: Sun Mar 01 09:32:20 2020"
    const dateMatch = line.match(/generated by 23andMe at:\s*(.+)/);
    if (dateMatch?.[1]) {
      const parsed = new Date(dateMatch[1]);
      if (!Number.isNaN(parsed.getTime())) {
        generationDate = parsed.toISOString().slice(0, 10);
      }
    }

    // Extract genome build: "build 37" or "build 38"
    const buildMatch = line.match(/build\s+(\d+)/);
    if (buildMatch?.[1]) {
      referenceGenome = `GRCh${buildMatch[1]}`;
    }
  }

  rl.close();
  stream.destroy();

  // Infer version from filename (v5, v4, etc.)
  const versionMatch = filePath.match(/_v(\d+)_/i);
  const sourceVersion = versionMatch?.[1] ? `v${versionMatch[1]}` : undefined;

  return {
    generationDate,
    referenceGenome,
    source: '23andMe',
    sourceVersion,
  };
}

/**
 * Parse a single data line from a 23andMe genome file.
 * Returns undefined for invalid/malformed lines.
 */
export function parseGenomeLine(
  rawLine: string,
  patientId: string,
  metadata: GenomeMetadata,
  importDate: string,
): GeneticVariant | undefined {
  const line = rawLine.replace(/\r/g, '').trim();

  // Skip empty lines and comments
  if (!line || line.startsWith('#')) return undefined;

  const parts = line.split('\t');
  if (parts.length < 4) return undefined;

  const [rsid, chromosome, positionStr, genotype] = parts;
  if (!(rsid && chromosome && positionStr && genotype)) return undefined;

  // Validate chromosome
  if (!VALID_CHROMOSOMES.has(chromosome)) return undefined;

  // Validate position
  const position = parseInt(positionStr, 10);
  if (Number.isNaN(position) || position < 0) return undefined;

  const variant: GeneticVariant = {
    id: randomUUID(),
    patientId,
    rsid,
    chromosome: chromosome as Chromosome,
    position,
    genotype,
    source: metadata.source,
    referenceGenome: metadata.referenceGenome,
    importDate,
  };

  if (metadata.sourceVersion) variant.sourceVersion = metadata.sourceVersion;

  return variant;
}

/**
 * Stream-parse a 23andMe genome file, yielding GeneticVariant objects.
 *
 * Uses AsyncGenerator for memory-efficient streaming — avoids loading 638K+
 * objects into memory at once.
 */
export async function* parseGenomeFile(
  filePath: string,
  patientId: string,
): AsyncGenerator<GeneticVariant> {
  const metadata = await parseGenomeMetadata(filePath);
  const importDate = new Date().toISOString();

  const stream = createReadStream(filePath, { encoding: 'utf-8' });
  const rl = createInterface({ input: stream, crlfDelay: Infinity });

  for await (const rawLine of rl) {
    const variant = parseGenomeLine(rawLine, patientId, metadata, importDate);
    if (variant) yield variant;
  }

  rl.close();
  stream.destroy();
}
